# Generated by Django 4.2.4 on 2023-08-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='task_id',
            field=models.IntegerField(),
        ),
    ]
