# Generated by Django 4.2.4 on 2023-08-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_order_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='task_id',
        ),
    ]
