# Generated by Django 4.2.4 on 2023-08-31 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_remove_order_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
